function(setup_fgfs_embedded_resources)
    # On Windows, make sure fgrcc can be run (it needs third-party libraries)
    if(MSVC)
      if (FINAL_MSVC_3RDPARTY_DIR)
        set(CMAKE_MSVCIDE_RUN_PATH ${FINAL_MSVC_3RDPARTY_DIR}/bin PARENT_SCOPE)
      else()
        message(FATAL_ERROR "FINAL_MSVC_3RDPARTY_DIR is empty or unset")
      endif()
    endif()
endfunction()

