/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: dds_gui.h
  Source: dds_gui.idl
  Cyclone DDS: V0.7.0

*****************************************************************/

#include "dds/ddsc/dds_public_impl.h"

#ifndef _DDSL_DDS_GUI_H_
#define _DDSL_DDS_GUI_H_


#ifdef __cplusplus
extern "C" {
#endif

#define FG_DDS_GUI_VERSION 1
#define FG_DDS_TANKS 8


typedef struct FG_DDS_GUI
{
  int16_t id;
  int16_t version;
  double longitude;
  double latitude;
  float altitude;
  float agl;
  float phi;
  float theta;
  float psi;
  float vcas;
  float climb_rate;
  uint16_t num_tanks;
  float fuel_quantity[8];
  uint64_t cur_time;
  uint64_t warp;
  float ground_elev;
  float tuned_freq;
  float nav_radial;
  bool in_range;
  float dist_nm;
  float course_deviation_deg;
  float gs_deviation_deg;
} FG_DDS_GUI;

extern const dds_topic_descriptor_t FG_DDS_GUI_desc;

#define FG_DDS_GUI__alloc() \
((FG_DDS_GUI*) dds_alloc (sizeof (FG_DDS_GUI)));

#define FG_DDS_GUI_free(d,o) \
dds_sample_free ((d), &FG_DDS_GUI_desc, (o))

#ifdef __cplusplus
}
#endif
#endif /* _DDSL_DDS_GUI_H_ */
