#!/bin/sh

# fgfs-shutdwon -- script to shutdown all the tile building clients and server
#
# Written by Curtis Olson, started May 1999.
#
# Copyright (C) 1999  Curtis L. Olson  - curt@flightgear.org
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# $Id$

SERVER=fgfs-tools-server

# check usage
if [ $# != 1 ]; then
    echo "Usage: $0 base_dir"
    exit
else
    BASE_DIR=$1
    WORK_BASE="${BASE_DIR}/work"
    MASTER_ON="${WORK_BASE}.status/MASTER_ON"
    echo "Base directory is $BASE_DIR"
    echo "Master ON file is $MASTER_ON"
fi

# remove the MASTER_ON switch so all the clients exit
echo "Removing the master switch file so all the clients will stop"
/bin/rm $MASTER_ON

# kill the server
echo "Killing the server"
killall $SERVER
