#ifndef _FG_ATIS_LEXICON_HXX
#define _FG_ATIS_LEXICON_HXX

#include <string>

// NOTE:  This file serves as a database.
// It is read by some utility programs that synthesize
// the library of spoken words.

#define Q(word) const std::string word(#word);

namespace lex {
Q(Airport)
Q(Airfield)
Q(Airbase)
Q(Junior)
Q(Celsius)
Q(Wind)
Q(zulu)
Q(zulu_weather)
Q(Automated_weather_observation)
Q(Weather)
Q(airport_information)
Q(International)
Q(Regional)
Q(County)
Q(Municipal)
Q(Memorial)
Q(Field)
Q(Air_Force_Base)
Q(Army_Air_Field)
Q(Marine_Corps_Air_Station)
Q(light_and_variable)
Q(at)
Q(thousand)
Q(hundred)
Q(zero)
Q(Temperature)
Q(clear)
Q(isolated)
Q(few)
Q(scattered)
Q(broken)
Q(overcast)
Q(thin)
Q(Sky_condition)
Q(Sky)
Q(Clouds)
Q(Ceiling)
Q(minus)
Q(Dewpoint)
Q(Visibility)
Q(less_than_one_quarter)
Q(one_quarter)
Q(one_half)
Q(three_quarters)
Q(one_and_one_half)
Q(Altimeter)
Q(QNH)
Q(Landing_and_departing_runway)
Q(Advise_on_initial_contact_you_have_information)
Q(This_is)
Q(information)
Q(millibars)
Q(hectopascal)
Q(inches)
Q(I_L_S)
Q(visual)
Q(cav_ok)
Q(clouds_and_visibility_OK)
Q(out)
Q(equals)
Q(Expect_I_L_S_approach)
Q(Expect_visual_approach)
Q(Transition_level)
Q(No_sig)
Q(Time)
Q(kelometers)
Q(Attention)
Q(flock_of_birds)
Q(bird_activity)
Q(in_the_vicinity_of_the_airport)
Q(short_time__I_LS_interference_possible_by_taxiing_aircraft)
Q(reed_back_all_runway_hold_instructions)
Q(glider_operation_in_sector)
Q(airport)
Q(runway_wet)
Q(runway_in_use)
Q(arrivals)
Q(runway)
Q(runways)
Q(expect)
Q(approach)
Q(departures)
Q(wet)
Q(ice)
Q(closed)
Q(light)
Q(moderate)
Q(heavy)
Q(rain)
Q(drizzle)
Q(snow)
Q(fog)
Q(plus)
Q(hours)
Q(variable)
Q(from)
Q(Or)
Q(And)
Q(to)
Q(maximum)
Q(between)
Q(degrees)
Q(or_more)
Q(left)
Q(right)
Q(center)
Q(knots)
}

#undef Q
#endif // _FG_ATIS_LEXICON_HXX
