#---------------------------------------------------------------------------
# Makefile
#
# Written by Curtis Olson, started March 1998.
#
# Copyright (C) 1997  Curtis L. Olson  - curt@me.umn.edu
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# $Id$
# (Log is kept at end of this file)
#---------------------------------------------------------------------------


ARLIBRARY = libDEM.a
TARGETS = $(ARLIBRARY)

CFILES =  dem.c leastsqs.c
CXXFILES = 

LDIRT = $(FG_ROOT_LIB)/$(ARLIBRARY)

include $(FG_ROOT_SRC)/commondefs

include $(COMMONRULES)


#---------------------------------------------------------------------------
# $Log$
# Revision 1.1  1998/03/19 02:54:46  curt
# Reorganized into a class lib called fgDEM.
#

