.\" Copyright (C) 2017 Alessandro Menti
.\"
.\" This program is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License
.\" as published by the Free Software Foundation; either version 2
.\" of the License, or (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
.\" Or try here: http://www.fsf.org/copyleft/gpl.html
.\"
.TH FGQCANVAS 1 2017-06-24 FlightGear "Pagine man di FlightGear"
.SH NOME
fgqcanvas \- Un'applicazione canvas remota basata su Qt per FlightGear
.SH SINTASSI
\fBfgqcanvas\fR
.SH DESCRIZIONE
.B fgqcanvas
è un'applicazione basata su Qt che può connettersi a una qualunque istanza di
FlightGear che abbia il server HTTPD incorporato abilitato e visualizzare un
qualunque canvas in tempo reale.
.PP
Per utilizzare \fBfgqcanvas\fR, avviarlo e immettere l'URL al socket Web HTTP,
ad esempio \fIws://localhost:8080/PropertyTreeMirror\fR, quindi immettere il
percorso al canvas che si desidera visualizzare, ad esempio
\fI/canvas/by-index/texture[0]/\fR.
.SH "STATI D'USCITA"
.B fgqcanvas
esce con
.B 0
se l'esecuzione ha avuto successo, con un codice d'uscita diverso da zero se si
è verificato un errore.
.SH "VEDERE ANCHE"
.BR fgfs (1)
