.\" Copyright (C) 2017 Alessandro Menti
.\"
.\" This program is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License
.\" as published by the Free Software Foundation; either version 2
.\" of the License, or (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
.\" Or try here: http://www.fsf.org/copyleft/gpl.html
.\"
.TH JS_DEMO 1 2017-06-24 FlightGear "Pagine man di FlightGear"
.SH NAME
js_demo \- Applicazione demo joystick per FlightGear
.SH SINTASSI
\fBjs_demo\fR
.SH DESCRIZIONE
.B js_demo
è un'utilità di FlightGear che visualizza i joystick rilevati e fornisce un
modo di monitorarli mentre li si muove lungo i loro assi o si premono i loro
pulsanti.
.SH "STATI D'USCITA"
.B js_demo
esce sempre con \fB0\fR.
.SH "VEDERE ANCHE"
.BR fgfs (1),
.UR http://\:wiki.flightgear.org/\:Input_device
la pagina "Input device" del wiki FlightGear
.UE
