// -*- coding: utf-8 -*-
//
// Header file automatically generated by fgrcc.
   
#ifndef _FG_FGDATA_EMBEDDED_RESOURCES
#define _FG_FGDATA_EMBEDDED_RESOURCES

void initFGDataEmbeddedResources();

#endif  // of _FG_FGDATA_EMBEDDED_RESOURCES
