.\" Copyright (C) 2017 Alessandro Menti
.\"
.\" This program is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License
.\" as published by the Free Software Foundation; either version 2
.\" of the License, or (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
.\" Or try here: http://www.fsf.org/copyleft/gpl.html
.\"
.TH FGQCANVAS 1 2017-02-28 FlightGear "FlightGear man pages"
.SH NAME
fgqcanvas \- A Qt-based remote canvas application for FlightGear
.SH SYNOPSIS
\fBfgqcanvas\fR
.SH DESCRIPTION
.B fgqcanvas
is a Qt-based application that can connect to any FlightGear instance having
the built-in HTTPD server enabled and display any canvas in real time.
.PP
To use \fBfgqcanvas\fR, start it and enter the URL to the HTTP websocket, such
as \fIws://localhost:8080/PropertyTreeMirror\fR, then enter the canvas path
you would like to display, such as \fI/canvas/by-index/texture[0]/\fR.
.SH "EXIT STATUS"
.B fgqcanvas
exits with
.B 0
on success, with an exit code other than zero if an error occurs.
.SH "SEE ALSO"
.BR fgfs (1)
