.\" Copyright (C) 2017 Alessandro Menti
.\"
.\" This program is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License
.\" as published by the Free Software Foundation; either version 2
.\" of the License, or (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
.\" Or try here: http://www.fsf.org/copyleft/gpl.html
.\"
.TH JS_DEMO 1 2017-03-04 FlightGear "FlightGear man pages"
.SH NAME
js_demo \- Joystick demo application for FlightGear
.SH SYNOPSIS
\fBjs_demo\fR
.SH DESCRIPTION
.B js_demo
is a FlightGear utility that shows detected joysticks and provides a way to
monitor them as their axes are moved or their buttons are pressed.
.SH "EXIT STATUS"
.B js_demo
always exits with \fB0\fR.
.SH "SEE ALSO"
.BR fgfs (1),
.UR http://\:wiki.flightgear.org/\:Input_device
the FlightGear wiki "Input device" page
.UE
