#ifndef FG_NO_VERSION_H
#define FG_NO_VERSION_H

// version.h is generated by the build system for official builds of
// FlightGear. To avoid complicating the life of regular developers,
// especially on Windows, we set HAVE_VERSION_H if version.h is generated.
// If that define is not set, we include this file instead, which provides
// placeholder values instead.

#define FLIGHTGEAR_VERSION "development " __DATE__
#define SIMGEAR_VERSION FLIGHTGEAR_VERSION

#define HUDSON_BUILD_NUMBER 0
#define HUDSON_BUILD_ID "none"
#define REVISION "unknown"

#endif
